export const JsonMock = {
    "data_to_show": [
      {
        "id": "01",
        "commerce": "Comercio 1",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 1,
        "last_sale": "13/04/2020"
      },
      {
        "id": "02",
        "commerce": "Comercio 2",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 1,
        "last_sale": "10/12/2020"
      },
      {
        "id": "03",
        "commerce": "Comercio 3",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 0,
        "last_sale": "22/05/2020"
      },
      {
        "id": "04",
        "commerce": "Comercio 4",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 1,
        "last_sale": "27/03/2020"
      },
      {
        "id": "05",
        "commerce": "Comercio 5",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 1,
        "last_sale": "27/03/2020"
      },
      {
        "id": "06",
        "commerce": "Comercio 6",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 1,
        "last_sale": "27/03/2020"
      },
      {
        "id": "07",
        "commerce": "Comercio 7",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 0,
        "last_sale": "27/03/2020"
      },
      {
        "id": "08",
        "commerce": "Comercio 8",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 1,
        "last_sale": "27/03/2020"
      },
      {
        "id": "09",
        "commerce": "Comercio 9",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 1,
        "last_sale": "27/03/2020"
      },
      {
        "id": "10",
        "commerce": "Comercio 10",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 1,
        "last_sale": "27/03/2020"
      },
      {
        "id": "11",
        "commerce": "Comercio 11",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 1,
        "last_sale": "27/03/2020"
      },
      {
        "id": "12",
        "commerce": "Comercio 12",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 1,
        "last_sale": "27/03/2020"
      },
      {
        "id": "13",
        "commerce": "Comercio 13",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 1,
        "last_sale": "27/03/2020"
      },
      {
        "id": "14",
        "commerce": "Comercio 14",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 1,
        "last_sale": "27/03/2020"
      },
      {
        "id": "15",
        "commerce": "Comercio 15",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 0,
        "last_sale": "27/03/2020"
      },
      {
        "id": "16",
        "commerce": "Comercio 16",
        "cuit": "cuit",
        "concept1": 1,
        "concept2": 2,
        "concept3": 3,
        "concept4": 4,
        "concept5": 5,
        "concept6": 6,
        "actual_balance": 123,
        "status": 1,
        "last_sale": "27/03/2020"
      }
    ],
    "rows_total": 16,
    "rows_per_page": 5,
    "sort": ["id","asc"]
  }